### ISSUE TITLE
Issues and Pull request are being counted twice

### ISSUE THREAD

**Issue by M-Zuber** [hahmed/Sprint#1]
[This](https://github.com/hahmed/Sprint/blob/master/Sprint/Views/Home/List.cshtml#L11) will display the count of all open issues **and** pull requests.
While I understand the reasoning behind having all in one list to print them out later on in the page, you also have a [list of open pull requests](https://github.com/hahmed/Sprint/blob/master/Sprint/Views/Home/List.cshtml#L15). This leads to some duplication of data.
In addition it would be nice to be able to tell from the list what is a PR and what is an issue. I understand that this app is more demo, so you may not want it to get too complicated so just an icon should be enough - no need for another list.

I make the following possible fixes (each one is a different option:
- When printing [the count here](https://github.com/hahmed/Sprint/blob/master/Sprint/Views/Home/List.cshtml#L11), filter to only count `Where(i => i.PullRequest == null)`
- Do the above mentioned filter in the controller already, and concat the lists when printing the full details
- Keep only one list and just filter it for the sake of the counts on the top of the page

Here is a screenshot with some links:
- repo: https://github.com/M-Zuber/todelete
- issues: https://github.com/M-Zuber/todelete/issues
- pull request: https://github.com/M-Zuber/todelete/pulls

![image](https://cloud.githubusercontent.com/assets/4746537/12646463/f02452f4-c5d8-11e5-82e5-e2945e2e88a1.png)

**Comment by hahmed** [comment]
Yep, that is a bug right there, I missed that one. I would filter this right in the controller.

I have actually been thinking about making this more than a sample, appreciate your feedback and would love a follow up PR.

<3

**Comment by hahmed** [comment]
With this sprint board the idea is to show the current issues that are open and which are being worked on, a PR is simply showing that some issue is being addressed - for now I will leave that out, however I may try and figure out how to show that in this sample.

I am open to ideas on how to make this a more rounded sample anyhow.

**Comment by M-Zuber** [comment]
Sorry I didn't get to it. I _will_ try and contribute something else in the project though.

**Comment by hahmed** [comment]
@M-Zuber It's cool, no worries, much appreciate you reporting the issue though, was working on a whole load of changes so I just fixed it.
